language: objective-c

before_install:
  - curl -o CI/Python.pkg https://www.python.org/ftp/python/2.7.11/python-2.7.11-macosx10.6.pkg
  - sudo installer -dumplog -package CI/Python.pkg -target /
  - sudo pip install requests
  - python ./CI/set_up.py

install:
  - sh CI/install.sh

script:
  - sh CI/build.sh

env:
    global:
      - secure: "IBffO275Px1rwaOjInp9eQA9Dtt66URRJTUuBphL1KcERil1I3xJwi6WHLexOHda355fIzosvYfpiMYrAQjKzSSfTq62YdtH0/lbObmlE66oNxiB5uySSesMiKcEYnFTpQ8Hbg+m7bas69sNDiOFze9IQf80zJ3PCuNWpODRc1F/38fNMfX0BGooX4WRB5uNNPL8oFIocUhCBvUPxg7bkvePn6e9UWtwgyX5fLYySlgQZ1d7EIpfniDLXzuXCwN2BEi0jrTTnDmNl6Hsjw0spMfQndpsvyOLF8ManQig83FkHrIo1AU9u+ZoGwOMvGOszLgjufraLAlgZOvGmw6wemIFLc3z47FlubYh3sOaqKVjoS0nPjfBBxn/554Qt1Iec9vXhF+HakT/Ygt127qd1Eh1xgV4vjXDihx1WhlTC7/9DTDNwu6pw2dQGbAL5l6fdpuBq25TAxIKI39EaOl1GyUDwnPdQYwjCsBFQqMTHuN0DbGScBT7YCrb+giAGxz76xrH4DoWwsFpT5uLe9G2puwQRy5im3TNFAcDwNmwsK5D1W5jHuV/Jb92ZPjtXNFtoZQTd7IVARvLM7uumHc/GpUgxbVPMReJJD3NlUNbzye3c0O9Z7uVs2BwTTXNBAW84vG083TU2SVeWgSpICoWiRZQkQVl87H/9ZHRpKsTgsY="
      - secure: "m1fOcbxzJrPtnNtNcJNYK2yG5EkkLt6J3RmSHx2cJHSampnxijE/NNqKgngadk/mscoOomvnnwbdYkt4lwve/lwADqoz8CQH1ikeDPecnyZBJPmI0WWOzsQ2qBqwHYsfboCSFBerhIMRi0k2htpHpvgq6utvmN9ZuGxMlFRbNLEDtoFiNRq+BrAtiFpL86MjLEQXKUWxbRdeSg18l7c3vs6GbN5sEuElId7QQx0Rl7mCBWICVBoUay8Bt0DLELtAmBeCvZDSLj+m4sSJXhz4S6wMhP8e+L2GWhq45/aizjg5W5UJlVL1eU5fRFSWjRQX3JLi98uOULExuQmQOGLYoggKswVzHzuzU7yRiBX/zC7viDuF6MduDxTjYIN+9TkdjXQ3Cuo/7fbH6tCmyM/ftlTJFIIJ+VrGiKmVdqZVn/mOyfCDnP6ObSWBfTrvRRNUUAc3EYMcqjCEZEdFIAO4Zt4s+HMD4Tb92om4OWkoYS4o5JzXxS866WGIJn4Z14Lcd++4vm2oBeIE9OBr2mZy6W5dc0E6HUKpnep9ZS0B0dBwdZVyxTeyIYdFRMoTe/XzH//EIR+4Vad+V9atKY4nvtHZMG60slfykFzfy0bbynR9Q6DLbuq3oTiWFpJnRFw9G3ndQU99BIXqkv3wk5AyabfHnQkWHkChvWXsw1+PMzk="
