language: objective-c

before_install:
  - curl -o CI/Python.pkg https://www.python.org/ftp/python/2.7.11/python-2.7.11-macosx10.6.pkg
  - sudo installer -dumplog -package CI/Python.pkg -target /
  - sudo pip install requests
  - python ./CI/set_up.py

install:
  - sh CI/install.sh

script:
  - sh CI/build.sh

env:
    global:
      - secure: "obEj3myWZ3bZunWwdnDRaAts3DgHBZOthROIeWWcJ2kRKhgOzAWDMmoU0VJ6FOTmoK3Gbq66eFNuRpQu1X9GQb6wcxhFveBDSok2/sxJGBnBsu6YlRd7NZsf8TxZ09l06f/c+rlNySgxjV2KAuHW+WhAi9mXLlYWSQLlhe6W2xPea3ziLWS1sjcc+nHkmxg95yMGDL4dvDWJiBHgzcoOg5jykklSSkXXJw+cYWB8XHfn0MrwfTGmALtVyhZ3LvBp0ieXjGRsfaloXM1i87OppdiTpuWwjAtGqZg/edGpf2NDMfdryEpPVVaYQTw/CXED0GCnZguZ3ixPA5ka/4HX60hlTsKEb8/ML1sYN6bv7ycMdHLU61S6qzgEnve5A0FQ0YYFG4Bd2CvNa/83k48yh7+6oyEIxCDznQI1Q7dVbvFrLEvpfmZEbnC6+3Rcazah1CFHfGkdLpqd3RPWJ6el0wl911iFpXryFc6x3eMJYvBtPUKmQfddQSGqJzF7EylG1XG/FD9i4GvrpjsBCHyAwGY5ohoc0mXSBFOBtUq0QFfXF+fS4zeqVAs0GFLMJig6Mb9tRg8rbz1NJBinDFWbXaUOy1jOh2x2BSvXJ7e9Gs48V7VNqHZr2RrkDkxdEubxYiLwDWJq18pwGqxcyFwWR9iPW8XgLjD37ScaBPKytIs="
      - secure: "m1fOcbxzJrPtnNtNcJNYK2yG5EkkLt6J3RmSHx2cJHSampnxijE/NNqKgngadk/mscoOomvnnwbdYkt4lwve/lwADqoz8CQH1ikeDPecnyZBJPmI0WWOzsQ2qBqwHYsfboCSFBerhIMRi0k2htpHpvgq6utvmN9ZuGxMlFRbNLEDtoFiNRq+BrAtiFpL86MjLEQXKUWxbRdeSg18l7c3vs6GbN5sEuElId7QQx0Rl7mCBWICVBoUay8Bt0DLELtAmBeCvZDSLj+m4sSJXhz4S6wMhP8e+L2GWhq45/aizjg5W5UJlVL1eU5fRFSWjRQX3JLi98uOULExuQmQOGLYoggKswVzHzuzU7yRiBX/zC7viDuF6MduDxTjYIN+9TkdjXQ3Cuo/7fbH6tCmyM/ftlTJFIIJ+VrGiKmVdqZVn/mOyfCDnP6ObSWBfTrvRRNUUAc3EYMcqjCEZEdFIAO4Zt4s+HMD4Tb92om4OWkoYS4o5JzXxS866WGIJn4Z14Lcd++4vm2oBeIE9OBr2mZy6W5dc0E6HUKpnep9ZS0B0dBwdZVyxTeyIYdFRMoTe/XzH//EIR+4Vad+V9atKY4nvtHZMG60slfykFzfy0bbynR9Q6DLbuq3oTiWFpJnRFw9G3ndQU99BIXqkv3wk5AyabfHnQkWHkChvWXsw1+PMzk="
